### ISSUE TITLE
psfex mode in PSF's currently leading to biased results

### ISSUE THREAD

**Issue by seccolf** [seccolf/mcal_sim_test#2]
The current implementation of the `psfex` mode for PSFs is leading to biased results in both `m` and `c`.

We did get unbiased results in the `psfex_deconvolved` mode but still need to dig more into the existing issue with the non-deconvolved version.

**Comment by seccolf** [comment]
Specifically, the current level of bias is:
```--------------------------
USING TILES:
--------------------------
DES2134-0124
DES2134+0126
--------------------------
GETTING MCAL FILES FROM:
/home/secco/project2-kicp-secco/delve/MCAL_OUTPUTS/v003_expgal_psfex
--------------------------
recovered g1= 0.019944 +/- 0.000008
trueg1=0.020
recovered g2= 0.000069 +/- 0.000005
trueg2=0.000
---------------------------------
size      N       = 177568
recovered (m - 1) = -2.783 +/- 1.135 [1e-3, 3-sigma]
recovered c       = 6.935 +/- 1.578 [1e-5, 3-sigma]

**Comment by DhayaaAnbajagane** [comment]
Bias is solved by passing in a psfex solution with pixel window func. deconvolved. Bias values below pass our tests:

```
size      N = 550489
recovered m = 0.194 +/- 0.283 [1e-3, 3-sigma]
recovered c = 0.061 +/- 0.560 [1e-5, 3-sigma]
```

It's likely there is some function in our pipeline and/or in a package used by pipeline that assumes `draw_method = 'auto'` instead of `draw_method = 'no_pixel'`. Passing in a deconvolved psf avoids this subtlety, so will use this version of inputs for the image pipeline now.
